common_parameters:
  base_data_directory_on_host: "../../data"
  logging_output_directory_on_host: "/tmp/voc_ssd"

voc:
  data_directory: "/data/VOC2012"
  train_set_path: "ImageSets/Main/train.txt"
  validation_set_path: "ImageSets/Main/val.txt"
  train_and_validation_set_path: "ImageSets/Main/trainval.txt"


log_path: "/tmp/voc_ssd.html"
training_history_log_path: "/tmp/voc_ssd_training_history_log.txt"

categories:
    ['background',
    'aeroplane',
    'bicycle',
    'bird',
    'boat',
    'bottle',
    'bus',
    'car',
    'cat',
    'chair',
    'cow',
    'diningtable',
    'dog',
    'horse',
    'motorbike',
    'person',
    'pottedplant',
    'sheep',
    'sofa',
    'train',
    'tvmonitor']

font_path: "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"

# Size factor to which images should be rescaled
size_factor: 32


vggish_model_configuration:
  prediction_heads_order: ["block2_pool", "block3_pool", "block4_pool", "block5_pool"]
  block2_pool:
    image_downscale_factor: 4
    base_bounding_box_sizes: [25]
    aspect_ratios: [0.6, 0.8, 1]
  block3_pool:
    image_downscale_factor: 8
    base_bounding_box_sizes: [40, 50, 60]
    aspect_ratios: [0.6, 0.8, 1]
  block4_pool:
    image_downscale_factor: 16
    base_bounding_box_sizes: [80, 100, 120]
    aspect_ratios: [0.6, 0.8, 1]
  block5_pool:
    image_downscale_factor: 32
    base_bounding_box_sizes: [150, 200, 300, 400, 500]
    aspect_ratios: [0.6, 0.8, 1]


resnetish_model_configuration:
  prediction_heads_order: ["res2c_branch2c", "res3b_branch2c", "res4b_branch2c", "res5b_branch2c"]
  res2c_branch2c:
    image_downscale_factor: 4
    base_bounding_box_sizes: [20, 30]
    aspect_ratios: [0.6, 0.8, 1]
  res3b_branch2c:
    image_downscale_factor: 8
    base_bounding_box_sizes: [40, 50, 60]
    aspect_ratios: [0.6, 0.8, 1]
  res4b_branch2c:
    image_downscale_factor: 16
    base_bounding_box_sizes: [70, 80, 100, 120]
    aspect_ratios: [0.6, 0.8, 1]
  res5b_branch2c:
    image_downscale_factor: 32
    base_bounding_box_sizes: [120, 150, 180, 200, 300, 400, 500]
    aspect_ratios: [0.6, 0.8, 1]


train:
  epochs: 100
  learning_rate: 0.00001
  early_stopping_patience: 5
  reduce_learning_rate_patience: 2
  reduce_learning_rate_factor: 0.1

model_checkpoint_path: "/data/voc_ssd_models/current_model.weights.h5"
best_model_checkpoint_path: "/data/voc_ssd_models/current_model/"
