voc:
  data_directory: "../../data/VOC2012"
  train_set_path: "ImageSets/Main/train.txt"
  validation_set_path: "ImageSets/Main/val.txt"
  train_and_validation_set_path: "ImageSets/Main/trainval.txt"

log_path: "/tmp/voc_ssd.html"

categories:
    ['background',
    'aeroplane',
    'bicycle',
    'bird',
    'boat',
    'bottle',
    'bus',
    'car',
    'cat',
    'chair',
    'cow',
    'diningtable',
    'dog',
    'horse',
    'motorbike',
    'person',
    'pottedplant',
    'sheep',
    'sofa',
    'train',
    'tvmonitor']

font_path: "/usr/share/fonts/truetype/msttcorefonts/arial.ttf"

# Size factor to which images should be rescaled
size_factor: 32


vggish_model_configuration:
    prediction_heads_order: ["block2_head", "block3_head", "block4_head", "block5_head"]
    block2_head:
      image_downscale_factor: 4
      base_bounding_box_sizes: [25]
      aspect_ratios: [0.4, 0.6, 0.8, 1]
    block3_head:
      image_downscale_factor: 8
      base_bounding_box_sizes: [30, 40, 50, 60]
      aspect_ratios: [0.2, 0.4, 0.6, 0.8, 1]
    block4_head:
      image_downscale_factor: 16
      base_bounding_box_sizes: [80, 100, 120]
      aspect_ratios: [0.2, 0.4, 0.6, 0.8, 1]
    block5_head:
      image_downscale_factor: 32
      base_bounding_box_sizes: [150, 200, 300, 400, 500]
      aspect_ratios: [0.2, 0.4, 0.6, 0.8, 1]


train:
  epochs: 200
  learning_rate: 0.00001
  early_stopping_patience: 5
  reduce_learning_rate_patience: 2
  reduce_learning_rate_factor: 0.1

model_checkpoint_path: "../../data/voc_ssd_models/current_model/"
best_model_checkpoint_path: "../../data/voc_ssd_models/current_model/"
