voc:
  data_directory: "../../data/VOC2012"
  train_set_path: "ImageSets/Main/train.txt"
  validation_set_path: "ImageSets/Main/val.txt"
  train_and_validation_set_path: "ImageSets/Main/trainval.txt"

log_path: "/tmp/voc_ssd.html"

categories:
    ['background',
    'aeroplane',
    'bicycle',
    'bird',
    'boat',
    'bottle',
    'bus',
    'car',
    'cat',
    'chair',
    'cow',
    'diningtable',
    'dog',
    'horse',
    'motorbike',
    'person',
    'pottedplant',
    'sheep',
    'sofa',
    'train',
    'tvmonitor']

font_path: "/Library/Fonts/Arial.ttf"

# Size factor to which images should be rescaled
size_factor: 32