voc:
  data_directory: "../../data/VOC2012"
  train_set_path: "ImageSets/Main/train.txt"
  validation_set_path: "ImageSets/Main/val.txt"
  train_and_validation_set_path: "ImageSets/Main/trainval.txt"

log_path: "/tmp/voc_ssd.html"

categories:
    ['background',
    'aeroplane',
    'bicycle',
    'bird',
    'boat',
    'bottle',
    'bus',
    'car',
    'cat',
    'chair',
    'cow',
    'diningtable',
    'dog',
    'horse',
    'motorbike',
    'person',
    'pottedplant',
    'sheep',
    'sofa',
    'train',
    'tvmonitor']

font_path: "/usr/share/fonts/truetype/msttcorefonts/arial.ttf"

# Size factor to which images should be rescaled
size_factor: 32

objects_filtering:
  minimum_size: 15
  minimum_aspect_ratio: 0.2
  maximum_aspect_ratio: 5


vggish_model_configuration:
    prediction_heads_order: ["block2_head", "block3_head", "block4_head"]
    block2_head:
      image_downscale_factor: 4
      base_bounding_box_sizes: [25]
      aspect_ratios: [1]
    block3_head:
      image_downscale_factor: 8
      base_bounding_box_sizes: [50]
      aspect_ratios: [0.4, 0.6, 1]
    block4_head:
      image_downscale_factor: 16
      base_bounding_box_sizes: [100, 80]
      aspect_ratios: [0.4, 0.6, 1]

